### ISSUE TITLE
NullReferenceException if ASPNETCORE_ENVIRONMENT is unset

### ISSUE THREAD

**Issue by TomasEkeli** [dolittle-interaction/AspNetCore#32]
https://github.com/dolittle-interaction/AspNetCore/blob/bee7c314d0db3aa0738ab9b0a4f6a3869b2bcda5/Source/Execution/ExecutionContextConfigurator.cs#L52

If you're running in a docker container with this unset (e.g. FROM microsoft/dotnet:2.2-sdk-bionic) you get a NullReferenceException.

The work-around is to set it in your dockerfile (ENV ASPNETCORE_ENVIRONMENT production), but we shouldn't crash if it is unset.

**Comment by woksin** [comment]
Ohh, yes. AspNetCore implementation needs the ASPNETCORE_ENVIRONMENT to be set in order to deduce the Environment
