### ISSUE TITLE
Upgrade to latest ASP.NET Core

### ISSUE THREAD

**Issue by einari** [dolittle-interaction/AspNetCore#58]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1124187404265272)

**Comment by smithmx** [comment]
We need this on Aksio.  We are using PolicySchemes ( https://docs.microsoft.com/en-us/aspnet/core/security/authentication/policyschemes?view=aspnetcore-2.2 ) and this was introduced in 2.1

Currently getting "lots" of warnings about mismatched versions, though it works.

**Comment by smithmx** [comment]
We're also getting an error in the "post build" step that it cannot load on of the dlls from aspnetcore (Microsoft.AspNetCore.Mvc.ViewFeatures) which means we have to disable this post-build step for things to work.  We can do this locally and in the docker file but the Azure Dev Ops build pipeline is continuously failing at the moment.

**Comment by einari** [comment]
Separating into a separate issue for the last comment; https://github.com/dolittle-runtime/DotNET.SDK/issues/221
