### ISSUE TITLE
Monitoring / Health endpoint

### ISSUE THREAD

**Issue by einari** [dolittle-interaction/AspNetCore#6]
child of https://github.com/dolittle-platform/home/issues/71

Expose a health endpoint by default so that we can monitor health from the outside.

The endpoint should just be a simple [middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.1&tabs=aspnetcore2x) returning 200 OK on a specific route.

The middleware should be added as the first thing we do in the `.UseDolittle()` extension.

It should not be protected and should be well defined on route - unchangeable. 

With that in place we have a convention for Web based solutions that we can recognize with Sentry even, so that we exclude that route from authentication. Plus our monitoring solutions can assume this route exists.

**Comment by woksin** [comment]
@einari where is the .UseDoLittle() extension defined?

**Comment by einari** [comment]
In `AppExtensions.cs`
